### ISSUE TITLE
Why do we have IDIDDocument, IPublicKey, IDIDDocumentProof in the Hive SDK?

### ISSUE THREAD

**Issue by BenjaminPiette** [elastos/Elastos.NET.Hive.JS.SDK#5]
Probably to be removed.

**Comment by carlduranleau** [comment]
Removed IDIDDocument.ts and added imports from did-js-sdk. There are missing exports in did-js-sdk, like the DIDDocumentService which is used in appcontext.ts. The IDIDDocument was including DIDDocumentProof, which is not exported from did-js-sdk. For now, it doesn't seem to be used, but we may have to export all DIDDocumentXXX classes from did-js-sdk.
